
ifneq ($(NDK_TOOLCHAIN_VERSION)$(ANDROID_TOOLCHAIN)$(ANDROID_BUILD_PATHS),)
L_CFLAGS := -DANDROID -DANDROID_LOG_TAG=\"BlackSiren\"
else
L_CFLAGS := -DANDROID_LOG_TAG=\"BlackSiren\"
endif

ifdef CONFIG_ANDROID_LOG
L_CFLAGS += -DCONFIG_ANDROID_LOG
endif

ifdef CONFIG_LEGACY_SIREN_TEST
L_CFLAGS += -DCONFIG_LEGACY_SIREN_TEST
endif

ifdef CONFIG_USE_FIFO
L_CFLAGS += -DCONFIG_USE_FIFO
endif

ifdef CONFIG_DEBUG_CHANNEL
L_CFLAGS += -DCONFIG_DEBUG_CHANNEL
endif

ifdef CONFIG_BACKUP_FILE_PATH
L_CFLAGS += -DCONFIG_BACKUP_FILE_PATH=\"$(CONFIG_BACKUP_FILE_PATH)\"
endif

ifdef CONFIG_REMOTE_CONFIG_FILE_URL
L_CFLAGS += -DCONFIG_REMOTE_CONFIG_FILE_URL=\"$(CONFIG_REMOTE_CONFIG_FILE_URL)\"
endif

ifdef CONFIG_STORE_FILE_PATH
L_CFLAGS += -DCONFIG_STORE_FILE_PATH=\"$(CONFIG_STORE_FILE_PATH)\"
endif

ifdef CONFIG_REMOTE_CONFIG_HOSTNAME
L_CFLAGS += -DCONFIG_REMOTE_CONFIG_HOSTNAME=\"$(CONFIG_REMOTE_CONFIG_HOSTNAME)\"
endif

ifdef CONFIG_USE_AD1
L_CFLAGS += -DCONFIG_USE_AD1
endif

ifdef CONFIG_USE_AD2
L_CFLAGS += -DCONFIG_USE_AD2
endif
ifdef CONFIG_TARGET_PRODUCT
ROKID_BLACKSIREN_CONFIG := $(CONFIG_TARGET_PRODUCT)
endif

ifdef CONFIG_BF_MVDR
L_CFLAGS += -DCONFIG_BF_MVDR
endif
